export const bryhada = [
  {
    name: "oleh",
    fullname: "Oleh Zapara",
    role: "Frontend & Backend Developer",
    imageUrl: "/images/oleh.jpg",
    skills: [
      "React",
      ".NET",
      "Typescript",
      "Next.js",
      "Rust",
      "C#",
      "Go",
      "Nest.js",
      "Express.js",
      "C",
      "C++",
    ],
    github: "https://github.com/OlehZapara",
    instagram: "https://www.instagram.com/olegzpr",
  },
  {
    name: "kyrylo",
    fullname: "Kyrylo Halyamov",
    role: "Frontend & Backend Developer",
    imageUrl: "/images/kyrylo.jpg",
    skills: [
      "Vue",
      "Typescript",
      "Nuxt",
      "C#",
      "React",
      "Next.js",
      "Nest.js",
      "C",
    ],
    github: "https://github.com/Kyryloloshka",
    instagram: "https://www.instagram.com/halyamovv/",
  },
  {
    name: "nata",
    fullname: "Nataliia Harashchuk",
    role: "Frontend Developer",
    imageUrl: "/images/nata.jpeg",
    skills: ["HTML", "CSS", "JavaScript"],
    github: "https://github.com/NataliaHarashchuk",
    instagram: "https://www.instagram.com/_.n._h_/",
  },
  {
    name: "arthur",
    fullname: "Artur Serkeli",
    role: "Frontend & Backend Developer",
    imageUrl: "/images/arthur.jpg",
    skills: [
      "HTML", 
      "CSS", 
      "JavaScript",
      "React",
      "Next.js",
      "Nest.js",
      "Express.js"
    ],
    github: "https://github.com/Artychanal",
    instagram: "https://www.instagram.com/artychanal/",
  },
  {
    name: "andrew",
    fullname: "Andrii Pasiura",
    role: "Frontend  Developer",
    imageUrl: "/images/andrew.jpg",
    skills: [
      "JavaScript",
      "Typescript",
      "React",
     "Next.js",
    ],
    github: "https://github.com/Andrii12390",
    instagram: "https://www.instagram.com/andrii_pasiura/",
  },
];
