version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: bryhada_server_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./apps/server/database/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pgdata:
